apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-onix-adapter-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: standard
  mountOptions:
    - implicit-dirs
    - file-cache:enable-parallel-downloads:true
    - file-cache:max-size-mb:-1
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: onix-adapter-bucket
  claimRef:
    name: gcs-fuse-onix-adapter-csi-static-pvc
    namespace: onix-adapter
