apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-onix-adapter-csi-static-pvc
  namespace: onix-adapter
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
